<?php

// config for Savannabits/Modular
return [
    'path' => 'modules',
    'namespace' => 'Modules',
    'vendor' => 'modular',
    'directory_tree' => [
        'bootstrap',
        'bootstrap/cache',
        'config',
        'database',
        'database/migrations',
        'database/seeders',
        'database/factories',
        'public',
        'resources',
        'resources/lang',
        'resources/views',
        'resources/js',
        'resources/css',
        'routes',
        'src',
        'src/Console',
        'src/Console/Commands',
        'src/Exceptions',
        'src/Facades',
        'src/Http',
        'src/Http/Controllers',
        'src/Models',
        'src/Policies',
        'src/Providers',
        'src/Support/Concerns',
        'src/Support/Contracts',
        'storage',
        'tests',
    ],
];
